web app to v2
bepronetwork/web-network pull request #384
Opened 2022-04-04 11:38 UTC by vhcsilva

2022-04-13 19:32 UTC, moshmage requested changes
lgtm, some changes needed but nothing major.

Also, group all the `todos` under one card @ notion so we can make new cards on the next daily session with all the todos so @clarkjoao and @MarcusviniciusLsantos can help out

2022-04-13 19:32 UTC, moshmage commented on package.json
> +    "@taikai/dappkit": "github:vhcsilva/dappkit#vhc_001_adding_status_methods",
dont forget to change to dappkit real ^^

2022-04-13 19:32 UTC, moshmage commented on pages/[network]/create-bounty.tsx
> +                      ALLOW_CUSTOM_TOKENS :
_i think_ that with V2 we can have all networks be a db value -- but this can be a change added later

2022-04-13 19:32 UTC, moshmage commented on pages/[network]/parity.tsx
> +import { NetworkFactory, toSmartContractDecimals } from "@taikai/dappkit";
with the `deploy` script and with the new environments this page can be removed :)

2022-04-13 19:32 UTC, moshmage commented on services/bepro-service.ts
> +  "disputableTime" |
missing spaces will confuse readers, easier to define a type with all these values,

```
type NetworkParameter: "councilAmount" | ...

async setNetworkParameter(param: NetworkParameter) {}
```

2022-04-18 20:57 UTC, moshmage commented on services/bepro-service.ts
> +    return BountyParser(await this.network.getBounty(id));
noes, no need to complicate; call this function `bounty` instead

2022-04-18 21:10 UTC, moshmage requested changes

2022-04-18 21:10 UTC, moshmage commented on pages/api/pull-request/index.ts
> +  if (networkBounty.pullRequests.find(pr =>
for sanity sake, assign the value on this condition to a variable and then if that variable (or simplify the if through better spacing, or make a function for the finder)

2022-04-22 09:42 UTC, moshmage approved these changes

2022-04-22 15:24 UTC, moshmage requested changes

2022-04-22 15:24 UTC, moshmage commented on pages/[network]/create-bounty.tsx
> +            dispatch(toastError(e.message || t("create-bounty:errors.creating-bounty")));
same here

2022-04-27 12:48 UTC, moshmage commented on components/change-token-modal.tsx
> +    if (!(isValidAddress === true)) return;
lol. sooo, `if (isValidAddress !== true)` ?

2022-04-27 13:05 UTC, moshmage approved these changes

2022-04-27 13:31 UTC, vhcsilva commented on components/pull-request-labels.tsx
> +    return t("status.conflicts");
Added a status to handle it, but only the Github GraphQL API provides a way to know if a PR needs approval

2022-04-27 15:24 UTC, merged