Dev 872 add nft uri to the close bounty action
bepronetwork/web-network pull request #598
Opened 2022-10-02 10:30 UTC by clarkjoao

2022-10-03 18:18 UTC, vhcsilva requested changes

2022-10-03 18:18 UTC, vhcsilva commented on pages/api/nft/index.ts
> +      const distributedAmount = networkBounty.tokenAmount * detail.percentage / 100;
use the function [calculateDistributedAmounts](https://github.com/bepronetwork/web-network/blob/dev/helpers/calculateDistributedAmounts.ts) to get the real paid amount

2022-10-03 22:26 UTC, moshmage requested changes

2022-10-03 22:26 UTC, moshmage commented on pages/api/nft/index.ts
> +    if (!networkBounty) return res.status(404).json("Invalid");
missing "nft already minted" logic

2022-10-03 22:34 UTC, moshmage requested changes

2022-10-03 22:34 UTC, moshmage commented on pages/api/nft/index.ts
> +    if(!proposal)
missing "proposal not disputed" logic, along with "proposal can be accepted"

2022-10-03 22:34 UTC, moshmage commented on pages/api/nft/index.ts
> +    const pullRequest = networkBounty.pullRequests.find(pr=> pr.id === proposal.prId)
missing denied/canceled/error logic for PR

2022-10-03 22:34 UTC, moshmage commented on pages/api/nft/index.ts
> +    return res.status(500).send(error);
should log this to elastic

2022-10-04 20:16 UTC, vhcsilva approved these changes

2022-10-04 20:16 UTC, vhcsilva commented on pages/api/nft/index.ts
> +      return res.status(404).json("proposal can be accepted");
```suggestion
      return res.status(404).json("proposal cannot be accepted");
```

2022-10-04 20:16 UTC, vhcsilva commented on pages/api/nft/index.ts
> +      return res.status(404).json("PR can be accepted");
```suggestion
      return res.status(404).json("PR cannot be accepted");
```

2022-10-05 09:12 UTC, moshmage reviewed
lgtm, just replace the "can" for "cannot" like @vhcsilva noted

2022-10-05 09:32 UTC, merged