DEV-896 fix load default settings
bepronetwork/web-network pull request #623
Opened 2022-10-17 17:06 UTC by clarkjoao

2022-10-17 17:18 UTC, vhcsilva requested changes

2022-10-17 17:18 UTC, vhcsilva commented on contexts/network-settings.tsx
> +      needed: BigNumber(registryCreatorAmount).toString(),
is better use `toFixed` instead of `toString`, in some cases `toString` can result in a scientific notation string

2022-10-17 17:18 UTC, vhcsilva commented on contexts/network-settings.tsx
> +      validated: BigNumber(tokensLockedInRegistry).isEqualTo(registryCreatorAmount),
```suggestion
      validated: BigNumber(tokensLockedInRegistry).isGreaterThanOrEqualTo(registryCreatorAmount),
```

2022-10-17 23:19 UTC, moshmage commented on contexts/network-settings.tsx
> +  const cleanStorage = () => localStorage.removeItem(`${localStorageKey}:${wallet.address}`)
use `WinStorage` class

2022-10-23 00:08 UTC, moshmage approved these changes

2022-10-24 08:32 UTC, merged