Bepro 1319 change network hero to calculate values from the api instead of querying chain
bepronetwork/web-network pull request #849
Opened 2023-01-30 22:19 UTC by MarcusviniciusLsantos

2023-01-31 08:45 UTC, moshmage requested changes

2023-01-31 08:45 UTC, moshmage commented on pages/api/header/networks/index.ts
> +    return res.status(404).json("Header information not found");
use `.json({message: "string"});` so json method is respected (or use `.text()` instead of `json()`)

2023-01-31 19:19 UTC, MarcusviniciusLsantos commented
> Missing calls that make the event run whenever a user opens a bounty or locks/unlocks tokens on a network so values are updated

we talked about not using it. In order not to fall into time-out. But I can follow and implement this logic inside events

2023-02-01 08:25 UTC, moshmage approved these changes

2023-02-02 12:25 UTC, merged