Bepro 1499 support multi network on my bounties and multi network design
bepronetwork/web-network pull request #926
Opened 2023-03-20 13:53 UTC by vhcsilva

2023-03-21 10:07 UTC, moshmage requested changes

2023-03-21 13:48 UTC, vhcsilva commented on components/profile/profile-router.tsx
> +  const routes = [
What you think of this way ?
```
const routes = [
    Route("/profile", ProfilePage),
    ...
  ];
//...
return <currentRoute.page />;
```

2023-03-21 14:40 UTC, moshmage commented on components/profile/profile-router.tsx
> +  const routes = [
That works too :)

2023-03-24 09:48 UTC, moshmage commented on pages/profile/[[...profilePage]].tsx
> +import { GetServerSideProps } from "next";
You can simply import the same `profile` component you created for `pages/[network]/[chain]/profile/[[...profilePage]].tsx` (or import this one on the previously mentioned)

2023-03-24 09:51 UTC, moshmage requested changes
looking good, just a minor detail about the profile pages and we're a-ok

2023-03-24 09:51 UTC, moshmage commented on pages/profile/[[...profilePage]].tsx
> +import { GetServerSideProps } from "next";
You can simply import the same `profile` component you created for `pages/[network]/[chain]/profile/[[...profilePage]].tsx` (or import this one on the previously mentioned)

2023-03-24 12:07 UTC, moshmage approved these changes

2023-03-24 12:09 UTC, merged