Bepro 1557 my netwok page new management tab design
bepronetwork/web-network pull request #988
Opened 2023-04-12 18:41 UTC by MarcusviniciusLsantos

2023-04-14 17:52 UTC, vhcsilva requested changes
I think that instead of passing `visible: true` every time we make a request, we could set `visible: true` as the default on all endpoints. In this way we guarantee that if we forget to pass this parameter, no hidden bounties will be returned.

2023-04-14 17:52 UTC, vhcsilva commented on components/list-issues.tsx
> +  const columns = ["Name", "Bounty Link", "Hide Bounty", "Cancel"];
Missing translation

2023-04-14 17:52 UTC, vhcsilva commented on components/profile/my-network-settings/index.tsx
> +        title: "Management",
Missing translation

2023-04-14 17:52 UTC, vhcsilva commented on pages/api/network/management/index.ts
> +    console.log(error);
use `Logger` service

2023-04-14 19:23 UTC, vhcsilva approved these changes

2023-04-20 22:09 UTC, moshmage approved these changes

2023-04-21 12:18 UTC, merged